import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Slideshow from '../components/slideshow'
import Nav from '../components/nav'
import Section1 from '../images/section1.png'
const inter = Inter({ subsets: ['latin'] })
import image1 from '../images/interact.jpg'
import AOS from 'aos'
import 'aos/dist/aos.css'
import react,{useEffect} from 'react'
export default function Home() {
  useEffect(() => {
    AOS.init();
  }, [])
  return (
    <>
      <Head>
        <title>Interact Club de Sousse Dossier Sponsoring</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Nav/>
        <Slideshow className={styles.main}/>
        <div className={styles.section1}>
          <div className={styles.section1color}></div>
          <div className={styles.section2color}></div>
          <Image data-aos="zoom-in" data-aos-duration="2000"  src={Section1} alt='section1' className={styles.section1img}/>
        </div>
        <div className={styles.section2}>
          <Image data-aos="fade-right" data-aos-duration="2000" src={image1} alt='section1' className={styles.section2img}/>
          <div data-aos="fade-left" data-aos-duration="2000"  className={styles.textsect2}>
            <h1 className={styles.titlesect2}>Notre Club</h1>
            <p>Notre club est composé de jeunes bénévoles engagés dans la communauté</p>
            <p>et travaillant à améliorer les vies des personnes les plus vulnérables.</p>
            <p>Nous croyons fermement que tout le monde mérite de vivre avec dignité,</p>
            <p>et c'est pourquoi nous organisons l'action Couffin Ramadan chaque année.</p>
          </div>
        </div>
        <div className={styles.section3}>
        <div data-aos="fade-right" data-aos-duration="2000"  className={styles.textsect2}>
            <h1 className={styles.titlesect3}>Idée General</h1>
            <p>Le Couffin Ramadan est une initiative organisée par le club Interact de Sousse.</p>
            <p>Son objectif est de collecter des dons en argent ou en nourriture pour les personnes dans le besoin pendant le mois sacré du Ramadan.</p>
            <p> Cette action vise à rassembler la communauté pour aider les moins fortunés et à montrer l'importance de la solidarité pendant ce temps de jeûne et de don.</p>
            <p>Les fonds et les denrées alimentaires collectés seront distribués à ceux qui en ont le plus besoin, offrant ainsi un soutien précieux.</p>
          </div>
          <Image data-aos="fade-left" data-aos-duration="2000" src={image1} alt='section1' className={styles.section3img}/>
        </div>
        <div className={styles.section4}>
          <h1 className={styles.titlesect4}>Notre besoin</h1>
          <div className={styles.parasect4}>
            <p>Nous sollicitons votre soutien pour cette initiative importante en demandant un don en argent ou en nourriture.</p>
            <p>Tout don, petit ou grand, fera une différence considérable dans la vie de ceux qui en ont besoin.</p>
            <p>Les fonds et les denrées alimentaires collectés seront distribués aux personnes les plus nécessiteuses,</p>
            <p>offrant ainsi un soutien précieux pour leur permettre de vivre avec dignité pendant ce mois de jeûne et de partage.</p>
          </div>
        </div>
      </main>
    </>
  )
}
